version: "3.8"

services:
  backend:
    build:
      context: ./backend/FitLog-spring-app
    container_name: fitlog-backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fitlog_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: fitlog_user
      SPRING_DATASOURCE_PASSWORD: fitlog_pass
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: "30000"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
    restart: always

  db:
    image: docker.io/mysql:8.2.0
    container_name: fitlog-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: fitlog_db
      MYSQL_USER: fitlog_user
      MYSQL_PASSWORD: fitlog_pass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MYSQL_ROOT_PASSWORD",
        ]
      interval: 5s
      timeout: 10s
      retries: 10
    restart: always

volumes:
  mysql_data:
